baseurl: "/" #"https://yxab.netlify.app/"
languageCode: "ru"
# language name
#languageName: "RU"
title: "Ухабы на дорогах"
theme: "hugo-paged"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: "↩"

outputs:
  home: [html, rss, json]

permalinks:
  ru: "/:sections/:year/:month/:slug/"
#  en: "/:sections/:year/:month/:slug/"

menu:
  main:
    - name: "Главная"
      url: "https://dvesti.github.io/yx" #"/"
      weight: 1
    - name: "О блоге"
      url: "/about/"
      weight: 5
    - name: "Архив"
      url: "/ru/"
      weight: 2
    - name: "Поиск"
      url: "/search/"
      weight: 6
    - name: "Категории"
      url: "/categories/"
      weight: 3
    - name: "Тэги"
      url: "/tags/"
      weight: 4
#    - name: "GitHub"
#      url: "https://github.com/dvesti/yx/"
#      weight: 4
#    - name: "Vitae"
#      url: "/vitae/"
#      weight: 4
#    - name: "Q&A"
#      url: "https://github.com/dvesti/yx/discussions/"
#      weight: 5
#    - name: "Todo"
#      url: "/todo/"
#      weight: 6
  ru:
    - name: "Главная"
      url: "/"
      weight: 1
    - name: "О блоге"
      url: "/about/"
      weight: 5
    - name: "Архив"
      url: "/ru/"
      weight: 2
    - name: "Поиск"
      url: "/search/"
      weight: 6
    - name: "Категории"
      url: "/categories/"
      weight: 3
    - name: "Тэги"
      url: "/tags/"
      weight: 4
#    - name: "GitHub"
#      url: "https://github.com/dvesti/yx/"
#      weight: 4
#    - name: "Vitae"
#      url: "/vitae/"
#      weight: 4
#    - name: "Q&A"
#      url: "https://github.com/dvesti/yx/discussions/"
#      weight: 5
#
#  knitr:
#    - name: "Home"
#      url: "/knitr/"
#      weight: 1
#    - name: "Options"
#      url: "/knitr/options/"
#      weight: 2
#    - name: "Hooks"
#      url: "/knitr/hooks/"
#      weight: 3
#    - name: "Examples"
#      url: "/knitr/demo/"
#      weight: 4
#    - name: "FAQ"
#      url: "/knitr/faq/"
#      weight: 5
#    - name: "Github"
#      pre: "github"
#      url: "https://github.com/yihui/knitr"
#      weight: 6
#    - name: "Yihui Xie"
#      url: "/"
#      weight: 7

params:
  description: "Yxab"
  footer: "&copy; 2023--{Year} [Dvesti](/)"
  customJS:
    - "comment-utils.js"
    - "hash-notes.js"
    - "toggle-notes.js"
    - "post-nav.js"
  logo:
    en:
      alt: YXAB
      img: "/images/logo.jpg"
      url: "/"
    ru:
      alt: YXAB
      img: "/images/logo.jpg"
      url: "/"
  githubContentURL: "https://github.com/dvesti/yx/tree/master/content/"
  twitterImage: "/images/logo.jpg"

#  logo:
#    en:
#    ru:
#    #  img: "/images/logo.png"
#    url: "/"
#    alt: Yxab
#    knitr:
#      img: "/knitr/images/knit-logo.png"
#      url: "/knitr/"
#      alt: "knitr logo"
#    tinytex:
#      img: "/images/logo-tinytex.png"
#      url: "/tinytex/"
#      alt: "tinytex logo"
#
  author:
    ru: Dvesti

  lang:
    edit:
      ru: "Правка"
    license:
      ru: "Лицензия"
    subscribe:
      ru: "RSS"
    search:
      ru: "Поиск"
    top:
      ru: "Вверх"
    tags:
      ru: тэг
    categories:
      ru: категория

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
    parser:
      autoHeadingIDType: blackfriday
  tableOfContents:
    startLevel: 1

